### ISSUE TITLE
How do i run it 

### ISSUE THREAD

**Issue by Soosman** [BRH-Media/Lego_Pak_Explorer#1]
How can i get it to work? There is no .exe to run the explorer.

**Comment by Brhsoftco** [comment]
We do not provide binaries for this project specifically; to get it to run, you need to download Visual Studio and build it using .NET 4.7.2 or higher.

**Comment by Soosman** [comment]
Thank you very much for that fast answer! 
Sadly im not at all capable of programming/coding, can i hope that there will be a full release of an .exe one day?
Edit: Grammar

**Comment by Brhsoftco** [comment]
I could certainly look into releasing a binary for this project; you should keep in mind that this mightn’t be overly stable though.

**Comment by Soosman** [comment]
That would be awesome! i dont really care if it is stable, im just excited for all the features :)
Thank you very much!

**Comment by Brhsoftco** [comment]
I would advise you to read the README on the front page; it contains a link to the formal build pipeline. You just need to download the artefacts.
